### ISSUE TITLE
Error in 08 - Load Balancer and Traffic Manager (az-101-03).md

### ISSUE THREAD

**Issue by TommyKobber** [MicrosoftLearning/AZ-103-MicrosoftAzureAdministrator#184] opened 2019-12-10 12:47 UTC
Exercise 0 task 1 and 2
When deploying the servers in both resource group it fails when the DSC package is being deployed. The error message in the Deployment details is 
"VM has reported a failure when processing extension 'dscExtension'. Error message: \"DSC Configuration 'ContosoWebsite' completed with error(s). Following are the first few: The request to add or remove features on the specified server failed.\r\nThe operation cannot be completed, because the server that you specified requires a restart.\n"
So apparently the servers being deployed needs a restart before installing the IIS role.

I haven't tried to do a manual deploy due to time constrains.

**Comment by polichtm** [comment] 2019-12-14 22:02
Hi Tommy,
again - I have no issues with this deployment. 
I guess one possibility is an OS update being applied following VM provisioning - but that's not something we can easily reproduce...
rgds
Marcin

**Comment by polichtm** [comment] 2019-12-19 02:23
Closing due to the inability to reproduce the issue

**Closed by polichtm** 2019-12-19 02:23 UTC
